CREATE DATABASE QLSANPHAM
USE QLSANPHAM

CREATE TABLE SANPHAM
(
    MASP INT IDENTITY(1,1) PRIMARY KEY,
    TENSP NVARCHAR(100),
    GIABAN FLOAT,
    SOLUONGTON INT
)
INSERT INTO SANPHAM
VALUES
(N'Samsung TV',25000000,5),
(N'LG TV',18000000,15),
(N'Sony TV',30000000,8),
(N'Toshiba TV',12000000,20)

CREATE FUNCTION FN_TINHTONG
(
	@A INT,
	@B INT
)
RETURNS INT
AS 
BEGIN
	RETURN @A +@B
END

SELECT dbo.FN_TINHTONG(2,3)

DECLARE CUR CURSOR
FOR 
SELECT TENSP
FROM SANPHAM

OPEN CUR
DECLARE @TENSP NVARCHAR(100)

FETCH NEXT FROM CUR INTO @TENSP

WHILE @@FETCH_STATUS =0
BEGIN
	PRINT @TENSP
	FETCH NEXT FROM CUR INTO @TENSP
END
CLOSE CUR
DELLOCATE CUR


BACKUP DATABASE QLCUAHANGDIENMAY
TO DISK ='D:\BACKUP\QLCHDM.BAK'

-------------------------------------------------------------------------
CREATE FUNCTION FN_THANHTIEN
(
	@GIABAN FLOAT,
	@SOLUONG INT
	)
RETURNS FLOAT
AS 
BEGIN
	RETURN @GIABAN *@SOLUONG
END
SELECT dbo.FN_THANHTIEN(150000,3)

CREATE FUNCTION FN_TINHKHUYENMAI
(
    @GIABAN FLOAT
)
RETURNS FLOAT
AS
BEGIN
    IF @GIABAN > 20000000
        RETURN @GIABAN * 0.1

    RETURN @GIABAN * 0.05
END

DECLARE CUR_SP CURSOR
FOR
SELECT TENSP, GIABAN
FROM SANPHAM

OPEN CUR_SP

DECLARE
    @TENSP NVARCHAR(100),
    @GIABAN FLOAT

FETCH NEXT FROM CUR_SP
INTO @TENSP, @GIABAN

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT N'Tên sản phẩm: ' + @TENSP

    PRINT N'Giá bán: '
        + CAST(@GIABAN AS NVARCHAR(30))

    PRINT '--------------------'

    FETCH NEXT FROM CUR_SP
    INTO @TENSP, @GIABAN
END

CLOSE CUR_SP
DEALLOCATE CUR_SP

DECLARE CUR_SP CURSOR
FOR
SELECT TENSP, SOLUONGTON
FROM SANPHAM

OPEN CUR_SP

DECLARE
    @TENSP NVARCHAR(100),
    @SOLUONGTON INT

FETCH NEXT FROM CUR_SP
INTO @TENSP, @SOLUONGTON

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @TENSP

    IF @SOLUONGTON < 10
        PRINT N'Sắp hết hàng'
    ELSE
        PRINT N'Còn hàng'

    FETCH NEXT FROM CUR_SP
    INTO @TENSP, @SOLUONGTON
END

CLOSE CUR_SP
DEALLOCATE CUR_SP

ALTER DATABASE QLCUAHANGDIENMAY
SET RECOVERY FULL

BACKUP DATABASE QLCUAHANGDIENMAY
TO DISK='D:\BACKUP\QLCHDM.BAK'

RESTORE DATABASE QLCUAHANGDIENMAY
FROM DISK='D:\BACKUP\QLCHDM.BAK'

CREATE FUNCTION FN_GIAMGIA
(
    @GIABAN FLOAT
)
RETURNS FLOAT
AS
BEGIN
    IF @GIABAN > 20000000
        RETURN @GIABAN * 0.1

    RETURN @GIABAN * 0.05
END

DECLARE CUR_SP CURSOR
FOR
SELECT TENSP
FROM SANPHAM

OPEN CUR_SP

DECLARE @TENSP NVARCHAR(100)

FETCH NEXT FROM CUR_SP INTO @TENSP

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT @TENSP

    FETCH NEXT FROM CUR_SP INTO @TENSP
END

CLOSE CUR_SP
DEALLOCATE CUR_SP

DECLARE CUR_SP CURSOR
FOR
SELECT TENSP, GIABAN, SOLUONGTON
FROM SANPHAM

OPEN CUR_SP

DECLARE
    @TENSP NVARCHAR(100),
    @GIABAN FLOAT,
    @SOLUONGTON INT

FETCH NEXT FROM CUR_SP
INTO @TENSP,@GIABAN,@SOLUONGTON

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT N'Tên SP: ' + @TENSP
    PRINT N'Giá bán: ' + CAST(@GIABAN AS NVARCHAR(30))
    PRINT N'Tồn kho: ' + CAST(@SOLUONGTON AS NVARCHAR(30))
    PRINT '----------------'

    FETCH NEXT FROM CUR_SP
    INTO @TENSP,@GIABAN,@SOLUONGTON
END

CLOSE CUR_SP
DEALLOCATE CUR_SP