-----------------1a------------------------
CREATE DATABASE QL_BANHANG
ON
(
	NAME=SALE_PRIMARY_LOGIC,
	FILENAME='D:\DATABASE\SALE_PRIMARY_PHYSICAL.mdf',
	SIZE=100MB,
	FILEGROWTH=10%,
	MAXSIZE=300MB
)
LOG ON
(
	NAME=SALE_LOG_LOGIC,
	FILENAME='D:\DATABASE\SALE_LOG_PHYSICAL.ldf',
	SIZE=50MB,
	FILEGROWTH=5%,
	MAXSIZE=200MB
)
------------------------1b---------------------
CREATE PROC PROC_TRAVEGIATRI
(
	@MADH CHAR(10)
)
AS
BEGIN	
	SELECT KHACH.HOTEN,CTDH.DONGIA
	FROM CHITIETDONHANG CTDH, KHACH,DONHANG DH
	WHERE CTDH.MADH=DH.MADH AND DH.MAKH=KHACH.MAKH
END

EXEC PROC_TRAVEGIATRI

-----------------------1C-------------------
CREATE FUNCTION FUNC_DONHANGCHUATHANHTOAN
(
	@THANG INT
)
RETURNS TABLE
AS
BEGIN

	SELECT DH.MADH ,DH.NGAYLAP ,DH.TRANGTHAI,HOTEN
	FROM DONHANG DH,KHACH K
	WHERE DH.MAKH=K.MAKH
END

--------------------------------ôn----------------------------------
--1a--
CREATE PROC SP_MADH
(
	@MADH CHAR(10),
	@HOTEN NVARCHAR(20) OUTPUT,
	@TRANGTHAI NCHAR(10) OUTPUT
)
AS
BEGIN
	SELECT @HOTEN=K.HOTEN,@TRANGTHAI=DH.TRANGTHAI
	FROM KHACH K,DONHANG DH
	WHERE K.MAKH=DH.MAKH
		AND MADH=@MADH
END


DECLARE @HOTEN NVARCHAR(20), @TRANGTHAI NCHAR(10)
EXEC SP_MADH 'DH001',@HOTEN OUTPUT,@TRANGTHAI OUTPUT

--1B--
CREATE PROC SP_MAKH
(
	@MAKH CHAR(10),
	@TONGSODONHANG INT OUTPUT,
	@DOANHTHU FLOAT OUTPUT
)
AS
BEGIN
	SELECT @TONGSODONHANG=COUNT(CTDH.MADH) ,@DOANHTHU=SUM(DONGIA*SOLUONG) 
	FROM CHITIETDONHANG CTDH,DONHANG DH
	WHERE MAKH=@MAKH AND CTDH.MADH=DH.MADH
END

DECLARE @TONGSODONHANG INT ,@DOANHTHU FLOAT
EXEC SP_MAKH 'KH001',@TONGSODONHANG OUTPUT,@DOANHTHU OUTPUT

-----1C---
CREATE FUNCTION SP_TIM
(
	@TRANGTHAI CHAR(10)
)
RETURNS TABLE
AS
RETURN
(
	SELECT DH.MADH,DH.NGAYLAP,DH.TRANGTHAI,K.HOTEN
	FROM DONHANG DH,KHACH K
	WHERE @TRANGTHAI=TRANGTHAI AND DH.MAKH=K.MAKH
)
SELECT* 
FROM dbo.SP_TIM(N'CHUA THANH TOAN')

CREATE FUNCTION FT_OK
(
	@MADH CHAR(10)
)
RETURNS FLOAT
AS
BEGIN
	DECLARE @TONGTIENDONHANG FLOAT
	SELECT @TONGTIENDONHANG=SUM(SOLUONG*DONGIA)
	FROM CHITIETDONHANG
	WHERE @MADH=MADH

	RETURN @TONGTIENDONHANG
END

SELECT dbo.FT_OK('DH001') AS TONGTIENDONHANG

-----------------------------CURSOR---------------------
DECLARE   CUR_DONHANG CURSOR
FOR 
SELECT MADH
FROM DONHANG

OPEN CUR_DONHANG 
DECLARE @MADH CHAR(10)
DECLARE @TONGTIEN FLOAT
FETCH NEXT FROM CUR_DONHANG INTO @MADH
WHILE @@FETCH_STATUS=0
BEGIN 
	SELECT @TONGTIEN=SUM(SOLUONG*DONGIA)
	FROM CHITIETHOADON
	WHERE @MADH=MADH

	IF @TONGTIEN>10000000
	UPDATE DONHANG
	SET TRANGTHAI=N'DON LON'
	WHERE @MADH=MADH
	
	ELSE 
	UPDATE DONHANG
	SET TRANGTHAI=N'DON THUONG'
	WHERE @MADH=MADH
	FETCH NEXT FROM CUR_DONHANG INTO @MADH
END
CLOSE CUR_DONHANG
DEALLOCATE CUR_DONHANG  


--------------TRIGGER-----------
CREATE TRIGGER CT_DONHANG
ON CHITIETHOADON
AFTER INSERT
AS
BEGIN 
	IF EXISTS
		(
			SELECT *
			FROM CHITIETHOADON
			WHERE SOLUONG <=0
		)
		BEGIN 
			PRINT N'SO LUONG LON HON 0'
			ROLLBACK TRANSACTION
		END
END

CREATE TRIGGER TG_KHACH
ON KHACH
AFTER INSERT
AS 
BEGIN
	IF EXISTS
	(
		SELECT *
		FROM inserted
		WHERE LOAIKH IS NULL
	)
	BEGIN
		UPDATE KHACH
		SET LOAIKH=N'PHO THONG'
		WHERE LOAIKH IS NULL
	END
END

---------------------------------CAU2----------------------
DECLARE CUR_CAPNHAT CURSOR
FOR
SELECT MAKH
FROM KHACH

OPEN CUR_CAPNHAT

DECLARE @MAKH CHAR(10)
DECLARE @DOANHTHU FLOAT

FETCH NEXT FROM CUR_CAPNHAT INTO @MAKH
WHILE @@FETCH_STATUS=0

BEGIN
	SELECT @DOANHTHU=SUM(SOLUONG*DONGIA)
	FROM CHITIETHOADON CTHD,DONHANG DG,KHACH K
	WHERE @MAKH=MAKH AND CTHD.MAHG=DG.MAHG AND DG.MAKH=K.MAKH

	IF @DOANHTHU<5000000
	UPDATE KHACH
	SET LOAIKH=N'PHOTHONG'
	WHERE MAKH=@MAKH

	ELSE IF @DOANHTHU<20000000
	UPDATE KHACH
	SET LOAIKH=N'THANH VIEN'
	WHERE MAKH=@MAKH

	ELSE 
	UPDATE KHACH
	SET LOAIKH=N'VIP'
	WHERE MAKH=@MAKH

	FETCH NEXT FROM CUR_CAPNHAT INTO @MAKH
END
CLOSE CUR_CAPNHAT
DEALLOCATE CUR_CAPNHAT


-------------------------------CAU3-----------------------------------
BACKUP DATABASE QL_BANHANG
TO DISK ='D:\BACKUP\QLBH_FULL_0000.bak'
WITH INIT

BACKUP LOG QL_BANHANG
TO DISK ='D:\BACKUP\QLBH_LOG1_09.trn'
WITH INIT
BACKUP DATABASE QL_BANHANG
TO DISK ='D:\BACKUP\QLBH_DIFF_12.bak'
WITH INIT,DIFFERENTIAL
BACKUP LOG QL_BANHANG
TO DISK ='D:\BACKUP\QLBH_LOG2_15.trn'
WITH INIT
BACKUP LOG QL_BANHANG
TO DISK ='D:\BACKUP\QLBH_LOG3_18.trn'
WITH INIT


RESTORE DATABASE QL_BANHANG
FROM DISK ='D:\RESORE\QLBH_FULL_0000.bak'
WITH NORECOVERY

RESTORE DATABASE QL_BANHANG
FROM DISK ='D:\RESTORE\QLBH_DIFF_12.bak'
WITH NORECOVERY

RESTORE LOG QL_BANHANG
FROM DISK ='D:\RESTORE\QLBH_LOG2_15.trn'
WITH RECOVERY

---------------------CAU4-------------------
CREATE LOGIN MINH
WITH PASSWORD='123'

CREATE LOGIN TUAN
WITH PASSWORD='1234'

CREATE USER MINH
FOR LOGIN MINH

CREATE USER TUAN 
FOR LOGIN TUAN
--------------------------------GRANT--------------
GRANT SELECT 
ON DONHANG
TO MINH
WITH GRANT OPTION

GRANT SELECT 
ON DONHANG
TO TUAN
WITH GRANT OPTION

GRANT SELECT 
ON KHACH
TO TUAN
WITH GRANT OPTION

GRANT SELECT 
ON KHACH
TO MINH
WITH GRANT OPTION
-----------------------------------------------------------------------
CREATE LOGIN LONG
WITH PASSWORD='134'

CREATE USER LONG
FOR LOGIN LONG

CREATE LOGIN NGOC
WITH PASSWORD='1234'

CREATE USER NGOC
FOR LOGIN NGOC

CREATE LOGIN THI
WITH PASSWORD='1234'

CREATE USER THI
FOR LOGIN THI

GRANT SELECT INSERT UPDATE 
ON DONHANG 
TO LONG

GRANT SELECT INSERT UPDATE 
ON DONHANG 
TO NGOC

GRANT SELECT INSERT UPDATE 
ON DONHANG 
TO THI

GRANT SELECT INSERT UPDATE 
ON CHITIETHOADON 
TO LONG

GRANT SELECT INSERT UPDATE 
ON CHITIETHOADON 
TO NGOC

GRANT SELECT INSERT UPDATE 
ON CHITIETHOADON 
TO THI
---------------------------------CAU5--------------------------------------












































